---
title: "Dowload"
author: "Gabriel Muñoz"
date: "12/3/2017"
output: html_document
---

# Download data 


Download TDWG World Geographical Scheme for Recording Plant Distributions Version 2.0: (Updated 19/12/01, minor errors fixed, and updated 15/03/2011 minor errors fixed)


[Level 1 ArcView shape file, zipped (2,351 Kb)](http://www.kew.org/gis/tdwg/downloads/level1.zip)

[Level 1-2 ArcView shape file, zipped (2,677 Kb)](http://www.kew.org/gis/tdwg/downloads/level2.zip)

[Level 1-3 ArcView shape file, zipped (3,642 Kb)](http://www.kew.org/gis/tdwg/downloads/level3.zip)

[Level 1-4 ArcView shape file, zipped (3,778 Kb)](http://www.kew.org/gis/tdwg/downloads/level4.zip)

## References & links:


Version 2. R. K. Brummitt with assistance from F. Pando, S. Hollis, N. A. Brummitt
and others. Plant Taxonomic Database Standards No. 2.ed. 2. World Geographical Scheme for Recording Plant Distributions, ed. 2.  2001. xv, 137 pp.; 17 maps. Stiff paper cover, $10.00. ISBN 0-913196-72-X.


Version 1. Hollis, S. & Brummitt, R. K., World Geographical Scheme for Recording Plant Distributions. Plant Taxonomic Database Standards No. 2. Version 1.0. 1992 Published for the International Working Group on Taxonomic Databases for Plant Sciences (TDWG) by the Hunt Institute for Botanical Documentation, Carnegie Mellon University, Pittsburg. 